name: Deploy Hugo to GithubPages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install hugo and build
        run: |
            sudo apt install hugo
            cd homepage
            hugo
      - name: Deploy to external repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.EXTERNAL_REPOSITORY_PERSONAL_ACCESS_TOKEN }}

        with:
          # GitHub Action output files
          source-directory: homepage/public
          destination-github-username: manuelNeidhart
          destination-repository-name: manuelNeidhart.github.io 
          user-email: lara.neidhart0508@gmail.com
          